### PR TITLE
src: update scheduledJobs in all cases

### PR DESCRIPTION
**Pull request by santigimeno**
- Whether a Job has been created via scheduleJob or Job.schedule.
- Add a new test.

### CODE REVIEW

**Comment by santigimeno** [comment]
Tries to fix https://github.com/tejasmanohar/node-schedule/issues/173

**Comment by tejasmanohar** [comment]
looks right to me but haven't gotten a chance to test it yet @santigimeno

**Comment by tejasmanohar** [comment]
yeah this works for me.

**Comment by santigimeno** [comment]
Merged: https://github.com/tejasmanohar/node-schedule/commit/1e7e09bfd8cf3a1538be803e10f29e795603602c

Cheers

**Pull request closed without merging**
