### PR TITLE
Quickfix for #179

### PR DESCRIPTION
**Pull request by seripap**
@santigimeno I'm not a fan of how the arguments are processed, but this should fix that issue for connivence jobs + naming them. If I have more time I would probably restructure how this is done, but for now it works.

### CODE REVIEW

**Comment by santigimeno** [comment]
@seripap thanks for the quick fix! I'll test it asap.
 I agree the arguments processing is not great, but tests should be added to avoid regressions. If you're up for the task it'd be great, if not I'll try to add them when I have time

**Comment by seripap** [comment]
@santigimeno agreed with tests, i'll be out of town this week, but I cleaned up the code a bit more. The tests should pass now :+1:

**Comment by seripap** [comment]
@santigimeno added your test case

**Comment by seripap** [comment]
The job [should also be passed](https://travis-ci.org/seripap/node-schedule)- not sure why it's failed here.

**Comment by tejasmanohar** [comment]
I can confirm that it also appears to be passing to me... hmm

**Pull request merged**
